server:
  port: 8080

# ======================================================================================================================
# dataSource


datasource:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/default?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true  # 数据库名称
    username: root
    password: 123456


