server:
  port: 8080

# ======================================================================================================================
# dataSource


datasource:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/default?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true  # 数据库名称
    username: root
    password: 123456

# ==========================================================================================================
# Redis 配置
redis:
  host: localhost # Redis服务器IP
  port: 6379 # Redis服务器端口
  password:
  database: 0 # 使用数据库的索引编号，一个示例有16个数据库 0 到 15
  lettuce:
    pool:
      max-active: 8 # 连接池的最大活动连接数量，使用负值无限制
      max-idle: 8  # 连接池的最大空闲连接数量，使用负值表示无限数量的空闲连接
      min-idle: 4 # 最小空闲连接数量，使用正值才有效果
      max-wait: -1ms # 连接池最大阻塞等待时间，使用负值表示没有限制
  ssl: false #是否启用SSL连接
  timeout: 5000 # 连接超时，毫秒为单位
#    sentinel:  #哨兵模式
#      master： 服务器名
#      nodes: 哨兵节点
#    cluster:
#      max-redirects: 5 #集群最大转发数
#      nodes: 集群节点
#    url:  Redis服务器的url 如: redis://user:password@example.com:6379


